language: node_js
node_js:
- lts/*
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
cache: yarn
env:
  global:
  - HEADLESS=true
  - secure: Yt3QqzTJMvnnxnvC+YcrbsI7B7Q1GJ2NHTgzq4iWXQw731dYlsgKfGgZt8bVkZf18GiPPcIDm8bZ2OBcgRy9j1sQZAMndIhQBf/VmQyZkuGfesvWyQ6+WTfGuT6V9KjF43kYzXNCwBgyFNdiwpiHvdhUvpbpAF1KiiDaNypivzS41ODb4nN5eobgY3a9jG+1+84vv0XsFbgdCExSsimMCsHflW6AOIhDbmMYbcVCj7QMMbo8R/62R4DE0765kGnUkYPRZuJW4K/siK7KpccdDEa525Wi3euVfeENOSoUgE8Gfkz1/ektluZUOSx+HHOOHMPvsQuyu3tfeImBa/LBxnwq5ViTq1iSUy9AohYxNapaK8iVwm0HCaaqMtVELVdHTwtcAAMuFp4aFhUM2wUod7WVmz9HjRn1K6n4eJYnyJ52G0qMx/fRemEHkq6g8QfwUBe6V+LcAuUZaYLiDN002huqKnHdbr8p6RDvTeDEvwH4dy1TeZDsJ/tVsr2DKeKOFkxqAIyEv/x3YkwzL0uKxbEUpklL0n6w3Xu+PrnzrnJ5SAVZFxUaFCoFOzb9prmSTNkd9V5qTG/8pC1aq/ZvqyuGHhv8golATWW1j3EI+vW+qs+MBEmpnHwgUpb5ngMeXN0lK9wE4AfW/RbD4ExVowKvMbhuCCLeRB1v0dcdyCo=
  - secure: ef+P5HobR5V6ppl7eTYglklITiE32pV3zeieLr1JVFdkYKKtgH+S3kInsHkhmtW1zCaaDWQJnLdnhd5k/elWmHmb6UV5VZ+bgHFxwJnFrAAIvVWl3mY5St6fBuODK2AN4bXvfPFzxOPnu8pmKn7odUDTspERzXFe6oJaGxw2udJt2rxRi7ihO0NxazEgp6QUR03ldrIflS1MTbEPukG04QoJrltUKqpXmtNKG9Tcp52TL2Y4ifNs1Jcligg1T8mOujwqQBLfIm5Tn3vfH68YDVKjBI/3HjLoOhdBBU3PPyqS069mXVbIrFWtAT2/6FrHK4gl+AFPEdGHExai0ptOZFs76821DvTULXedE3/oWUW/l+6E2TfjpgxLt6BZXw9tMDBCBSovG3iNfYt36KXKRFlyWLrw7EbhT8mGmektUv3wmB5Rkgn4Y6d25dQPMcLRdSHKR3y354dcC0PCEn84t2lfwYWeLNdJ43XLRytifldcqQLqhlDrkZqlOZg8DWF3peQezRROzHrH9pSUJXYnXotxCH2EKyK9256X6s9PBe9L7ywTk7s1k+qxUN5088lcnaxwVovqKrI6VW4jsWqRJnhHOxNeIfe+k1h5HaFzy6i5BaZwox0t7b89kTZFzG5EyEydltZn/QaUK8FtdwlkGQLU2qfA9VoM0zcWPaNVinU=
