version: "3"
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db:Z
        network_mode: host
        logging:
            driver: none
        command: --bind_ip_all

    mongo-express:
        image: mrvautin/adminmongo
        depends_on:
            - mongo
        ports:
            - "1234:1234"
        network_mode: host
        logging:
            driver: none
        command: /bin/sh -c "rm ./config/app.json && node app.js"
        environment:
            - CONN_NAME=HelloWorld
            - DB_HOST=mongo
            - DB_PORT=27017
            - DB_NAME=HelloWorld

    app:
        tty: true
        stdin_open: true
        container_name: app
        build:
            context: ./
        command: yarn dev
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        depends_on:
            - mongo-express
        ports:
            - "5000:5000"
            - "9229:9229"
            - "5858:5858"
        network_mode: host
