version: '3'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db:Z
        logging:
            driver: none

    mongo-express:
        image: mrvautin/adminmongo
        depends_on:
            - mongo
        ports:
            - '1234:1234'
        network_mode: host
        logging:
            driver: none
        command: /bin/sh -c "node app.js && rm ./config/app.json"
        environment:
            - CONN_NAME=HelloWorld
            - DB_HOST=localhost
            - DB_PORT=27017
            - DB_NAME=HelloWorld

    app:
        container_name: app
        build:
            context: ./
        command: yarn dev
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        depends_on:
            - mongo-express
            # - mongo
        ports:
            - '5000:5000'
            - '9229:9229'
            - '5858:5858'
        network_mode: host
        # env_file: ./.env # TODO - uncomment this to auto-load your .env file!
        environment:
            - DB=mongodb://localhost:27017/HelloWorld
